spring.application.name=api-gateway

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# JWT
jwt.secret=${JWT_SECRET:ec8f6db42ad249867086afd13e35138d68af4809835fed8236693add84d81ea9}

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
